[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "20"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Redirect API requests to the Netlify function
[[redirects]]
  from = "/api/groq"
  to = "/.netlify/functions/groq-proxy"
  status = 200